### ISSUE TITLE
Cannot open .curxptheme

### ISSUE THREAD

**Issue by TomJansen** [TomJansen/GursorMaker#1]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/GursorMaker/GursorMaker.py", line 264, in ImportCurXP
    ImportCursorXPTheme(self.cursorData, self.cursorList, self.cursorSubList)
  File "/usr/local/lib/python2.7/dist-packages/GursorMaker/curxp.py", line 32, in ImportCursorXPTheme
    os.chdir(fw.get_current_folder())
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

In addition, cannot click open or cancel in the file opener

**Comment by TomJansen** [comment]
This happens only when using the "recently used" folder in the side panel of the file chooser
